name: redurx
version: 1.1.0
description: A thin layer of a Redux-based state manager on top of RxDart.
author: leocavalcante <lc@leocavalcante.com>
homepage: https://github.com/leocavalcante/ReduRx

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  rxdart: ^0.20.0

dev_dependencies:
  test: ^1.5.1+1
